Reviewss
oreyes1991/pueblo_pequeno pull request #22
Opened 2023-03-19 23:25 UTC by LuisDZurita

hello.
we just add some changes on the footer and we add a new "ayuda" page. Juste let me know if is something is wrong.
thanks!

2023-03-22 21:04 UTC, oreyes1991 requested changes
Good job man, I just left some small change requests

2023-03-22 21:04 UTC, oreyes1991 commented on Ayuda.html
> +            <li><a href="mailto:wilber@gmail.com">wilber@gmail.com</a></li>
Just curious, why this is repeated?  how come is not just one link?

2023-03-22 21:04 UTC, oreyes1991 commented on cabanas.html
> +        <h2>el guevo!!</h2>
we should start removing this testing text, if there is still not clear what is going to be here we should replace it for a `Lorem Ipsum`

2023-03-22 21:04 UTC, oreyes1991 commented on cabanas.html
> +      <p>copyRai "BBCoffe" 2022</p>
can we get rid of this?

2023-03-22 21:04 UTC, oreyes1991 commented on codejs.js
> +const Xboton = document.querySelector(".Xboton");
nit: const in JS should be camel case
```suggestion
const xButton = document.querySelector(".Xboton");
```

2023-03-22 21:04 UTC, oreyes1991 commented on codejs.js
> +  });
nit: strings in JS should be single quote, not double.
```suggestion
  aCabana.addEventListener('click', () => {
    currentCabana = i;
    poput.classList.remove('hide');
  });
```

2023-03-22 21:04 UTC, oreyes1991 commented on codejs.js
> +  });
nit: same here
```suggestion
if (xButton) {
  xButton.addEventListener('click', () => {
    poput.classList.add('hide');
  });
```

2023-03-22 21:04 UTC, oreyes1991 commented on codejs.js
> +    imgFullScren: "img/cabana2.jpg",
nit: this should also be single quotes.

2023-03-22 21:04 UTC, oreyes1991 commented on codejs.js
> +const mainGallery = document.querySelector(".gallery");
same here

2023-03-22 21:04 UTC, oreyes1991 commented on index.html
> +    />
Niceee 😄

2023-03-22 22:01 UTC, LuisDZurita commented on cabanas.html
> +        <h2>el guevo!!</h2>
I'm really sorry. we delete this page.

2023-03-24 22:07 UTC, oreyes1991 approved these changes

2023-03-24 23:33 UTC, merged